version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu